apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronus-api
spec:
  selector:
    matchLabels:
      app: cronus-api
  replicas: 2
  template:
    metadata:
      labels:
        app: cronus-api
    spec:
      containers:
      - name: cronus-api
        image: toptop/cronus-api:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8844